/**
 * Config → generated TypeScript file content.
 *
 * See docs/architecture/ENGINES_AND_CLI_PLAN.zh.md §5.5 for the output shape.
 */

import { createHash } from 'node:crypto';
import type { SupramarkConfig, EchartsChart, EchartsComponent } from './types.js';

const ECHARTS_CHARTS_ALL: EchartsChart[] = [
  'Line', 'Bar', 'Pie', 'Scatter', 'EffectScatter', 'Radar',
  'Tree', 'TreeMap', 'Sunburst', 'Boxplot', 'Candlestick',
  'Heatmap', 'Map', 'Parallel', 'Lines', 'Graph', 'Sankey',
  'Funnel', 'Gauge', 'PictorialBar', 'ThemeRiver', 'Custom',
];

const ECHARTS_COMPONENTS_ALL: EchartsComponent[] = [
  'Grid', 'Polar', 'GeoComponent', 'SingleAxis', 'Parallel',
  'Calendar', 'Graphic', 'Toolbox', 'Tooltip', 'AxisPointer',
  'Brush', 'Title', 'Timeline', 'MarkPoint', 'MarkLine', 'MarkArea',
  'Legend', 'DataZoom', 'VisualMap', 'Dataset', 'Transform', 'Aria',
];

export interface GenerateInput {
  config: SupramarkConfig;
  /** CLI version — written into the file header for traceability */
  cliVersion: string;
  /** Raw config JSON string (used to compute the hash) */
  configSource: string;
  /** Relative path of the original config file (written into the file header) */
  configPath: string;
}

export function generate(input: GenerateInput): string {
  const { config, cliVersion, configSource, configPath } = input;
  const hash = createHash('sha256').update(configSource).digest('hex').slice(0, 16);
  const platform = config.platform ?? 'web';
  const supramarkPkg = platform === 'rn' ? '@supramark/rn' : '@supramark/web';

  // Collect all import statements (grouped)
  const coreImports: string[] = [];
  const engineFactoryImports: string[] = [];
  const engineDepImports: string[] = [];
  const engineAssignments: string[] = [];

  coreImports.push(`import { createRender, createSupramark } from '${supramarkPkg}/createSupramark';`);

  // -- Mermaid
  if (truthy(config.mermaid)) {
    engineFactoryImports.push(`import mermaid from '@supramark/engines/mermaid';`);
    engineAssignments.push(`  mermaid: mermaid(),`);
  }

  // -- MathJax (auto-loaded when the math feature is enabled)
  const mathOn = config.mathjax === true || truthy(config.features?.math);
  if (mathOn) {
    engineFactoryImports.push(`import mathjax from '@supramark/engines/mathjax';`);
    engineAssignments.push(`  math: mathjax(),`);
  }

  // -- Graphviz
  if (config.graphviz === 'web' || config.graphviz === 'rn') {
    const adapterPath =
      config.graphviz === 'rn' ? 'rn-adapter' : 'web-adapter';
    engineFactoryImports.push(`import graphviz    from '@supramark/engines/graphviz';`);
    engineDepImports.push(`import gvAdapter   from '@supramark/engines/graphviz/${adapterPath}';`);
    engineAssignments.push(`  dot:      graphviz([gvAdapter]),`);
    engineAssignments.push(`  graphviz: graphviz([gvAdapter]),`);
  }

  // -- ECharts
  if (config.echarts) {
    const charts = config.echarts.charts === '*' ? ECHARTS_CHARTS_ALL : config.echarts.charts;
    const components =
      config.echarts.components === '*'
        ? ECHARTS_COMPONENTS_ALL
        : config.echarts.components ?? [];
    const renderers = (config.echarts.renderers ?? ['svg']).map(r =>
      r === 'canvas' ? 'CanvasRenderer' : 'SVGRenderer'
    );

    engineFactoryImports.push(`import echarts     from '@supramark/engines/echarts';`);
    engineDepImports.push(`import * as echartsCore from 'echarts/core';`);
    if (charts.length > 0) {
      engineDepImports.push(
        `import { ${charts.map(c => `${c}Chart`).join(', ')} } from 'echarts/charts';`
      );
    }
    if (components.length > 0) {
      engineDepImports.push(
        `import { ${components.map(c => `${c}Component`).join(', ')} } from 'echarts/components';`
      );
    }
    engineDepImports.push(
      `import { ${renderers.join(', ')} } from 'echarts/renderers';`
    );

    const moduleList = [
      'echartsCore',
      ...renderers,
      ...charts.map(c => `${c}Chart`),
      ...components.map(c => `${c}Component`),
    ];
    engineAssignments.push(`  echarts:  echarts([${moduleList.join(', ')}]),`);
  }

  // -- Vega-Lite
  if (truthy(config['vega-lite'])) {
    engineFactoryImports.push(`import vegaLite    from '@supramark/engines/vega-lite';`);
    engineDepImports.push(`import * as Vega     from 'vega';`);
    engineDepImports.push(`import * as VegaLite from 'vega-lite';`);
    engineAssignments.push(`  'vega-lite': vegaLite([Vega, VegaLite]),`);
  }

  // features section
  const featuresJson = JSON.stringify(config.features ?? {}, null, 2)
    .replace(/^/gm, '  ')
    .trim();

  return `// AUTO-GENERATED by @supramark/cli v${cliVersion}
// Source: ${configPath} (sha256: ${hash})
// Do not edit manually. Re-run: bun x supramark-gen
/* eslint-disable */

${coreImports.join('\n')}

${engineFactoryImports.length > 0 ? engineFactoryImports.join('\n') + '\n' : ''}${engineDepImports.length > 0 ? engineDepImports.join('\n') + '\n' : ''}
const spec = {
  engines: {
${engineAssignments.join('\n')}
  },
  features: ${featuresJson},
} as const;

export const render    = createRender(spec);
export const Supramark = createSupramark(spec);

export type { RenderOptions } from '@supramark/engines/types';
`;
}

export function computeHash(source: string): string {
  return createHash('sha256').update(source).digest('hex').slice(0, 16);
}

function truthy(value: unknown): boolean {
  return value === true || (typeof value === 'object' && value !== null);
}
