#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.join(__dirname, '..');

interface PackageInfo {
  name: string;
  path: string;
}

const PACKAGES: PackageInfo[] = [
  { name: 'core', path: 'packages/core' },
  { name: 'web', path: 'packages/renderers/web' },
  { name: 'rn', path: 'packages/renderers/rn' },
];

const docsDir = path.join(projectRoot, 'docs/api');
fs.mkdirSync(docsDir, { recursive: true });

console.log('🚀 Generating API docs...\n');

interface JSDocBlock {
  description: string;
  tags: Record<string, string[]>;
  declaration: string;
}

function extractJSDocBlocks(content: string): JSDocBlock[] {
  const blocks: JSDocBlock[] = [];
  const jsdocRegex = /\/\*\*\s*\n([\s\S]*?)\*\/\s*\n\s*export\s+([\s\S]*?)(?=\n\/\*\*|\nexport|$)/g;

  let match;
  while ((match = jsdocRegex.exec(content)) !== null) {
    const [, comment, declaration] = match;

    const lines = comment
      .split('\n')
      .map(line => line.replace(/^\s*\*\s?/, '').trim())
      .filter(Boolean);

    const description: string[] = [];
    const tags: Record<string, string[]> = {};

    for (const line of lines) {
      if (line.startsWith('@')) {
        const [tag, ...value] = line.split(/\s+/);
        const tagName = tag.slice(1);
        if (!tags[tagName]) tags[tagName] = [];
        tags[tagName].push(value.join(' '));
      } else {
        description.push(line);
      }
    }

    blocks.push({
      description: description.join(' '),
      tags,
      declaration: declaration.trim(),
    });
  }

  return blocks;
}

function generateAPIDoc(content: string, pkg: PackageInfo): string {
  let doc = `# @supramark/${pkg.name}\n\n`;
  const jsdocBlocks = extractJSDocBlocks(content);

  if (jsdocBlocks.length > 0 && jsdocBlocks[0].description) {
    doc += `${jsdocBlocks[0].description}\n\n`;
  }

  doc += `## Installation\n\n`;
  doc += `\`\`\`bash\n`;
  doc += `bun add @supramark/core @supramark/${pkg.name}\n`;
  doc += `\`\`\`\n\n`;

  doc += `## Main Exports\n\n`;
  doc += `> **Note**: for the full type definitions, see the [TypeDoc API docs](/typedoc/)\n\n`;

  for (const block of jsdocBlocks) {
    if (!block.declaration) continue;

    const nameMatch = block.declaration.match(/(?:function|class|const|type|interface)\s+(\w+)/);
    const name = nameMatch ? nameMatch[1] : 'Unknown';

    doc += `### \`${name}\`\n\n`;

    if (block.description) {
      doc += `${block.description}\n\n`;
    }

    if (block.tags.param) {
      doc += `**Parameters:**\n`;
      for (const param of block.tags.param) {
        doc += `- ${param}\n`;
      }
      doc += `\n`;
    }

    if (block.tags.returns) {
      doc += `**Returns:**\n`;
      for (const ret of block.tags.returns) {
        doc += `- ${ret}\n`;
      }
      doc += `\n`;
    }
  }

  doc += `## Related Resources\n\n`;
  doc += `- [TypeDoc API Docs](/typedoc/)\n`;
  doc += `- [Features Docs](/features/)\n`;
  doc += `- [Getting Started](/guide/getting-started)\n\n`;
  doc += `---\n*This document is auto-generated by scripts/doc-gen-api.ts*\n`;

  return doc;
}

for (const pkg of PACKAGES) {
  console.log(`📦 Processing package: @supramark/${pkg.name}`);

  try {
    const indexPath = path.join(projectRoot, pkg.path, 'src/index.ts');
    const content = fs.readFileSync(indexPath, 'utf-8');
    const docContent = generateAPIDoc(content, pkg);
    const outputPath = path.join(docsDir, `${pkg.name}.md`);
    fs.writeFileSync(outputPath, docContent);
    console.log(`  ✅ Generated api/${pkg.name}.md`);
  } catch (err) {
    console.error(`  ❌ Failed: ${err instanceof Error ? err.message : String(err)}`);
  }
}

console.log('\n✅ API docs generation complete!');
