import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import type { ContainerExtensionSpec } from '../packages/core/src/container-extension';

const repoRoot = process.cwd();
const featuresRoot = path.join(repoRoot, 'packages', 'features', 'container');
const outDir = path.join(repoRoot, 'generated');

function ensureDir(p: string) {
  fs.mkdirSync(p, { recursive: true });
}

function listFeatureDirs(): string[] {
  if (!fs.existsSync(featuresRoot)) return [];
  return fs
    .readdirSync(featuresRoot, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);
}

async function loadExtensionSpec(dirName: string): Promise<ContainerExtensionSpec | null> {
  const extTs = path.join(featuresRoot, dirName, 'src', 'extension.ts');
  if (!fs.existsSync(extTs)) return null;

  // 直接 import TS 源码：由 bunx tsx 执行，支持 ts/esm
  const mod: any = await import(pathToFileURL(extTs).href);
  const spec = mod.extension as ContainerExtensionSpec | undefined;
  return spec ?? null;
}

function validateSpec(spec: ContainerExtensionSpec, source: string) {
  if (spec.kind !== 'container') throw new Error(`Invalid kind in ${source}`);
  if (!spec.featureId) throw new Error(`Missing featureId in ${source}`);
  if (!spec.nodeName) throw new Error(`Missing nodeName in ${source}`);
  if (!Array.isArray(spec.containerNames) || spec.containerNames.length === 0) {
    throw new Error(`Missing containerNames in ${source}`);
  }
  if (!spec.parserExport) throw new Error(`Missing parserExport in ${source}`);
  if (!spec.webRendererExport) throw new Error(`Missing webRendererExport in ${source}`);
  if (!spec.rnRendererExport) throw new Error(`Missing rnRendererExport in ${source}`);
}

function genParsers(specs: ContainerExtensionSpec[]) {
  const lines: string[] = [];
  lines.push('/* AUTO-GENERATED. DO NOT EDIT. */');
  lines.push('// Generated by scripts/generate-container-registry.ts');
  lines.push('');

  specs.forEach((s, i) => {
    lines.push(`import { ${s.parserExport} as p${i} } from '../packages/features/container/${s.featureDir}/src/syntax';`);
  });

  lines.push('');
  lines.push('export function registerAllContainerParsers() {');
  specs.forEach((_, i) => lines.push(`  p${i}();`));
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

function genRenderers(specs: ContainerExtensionSpec[], platform: 'web' | 'rn') {
  const lines: string[] = [];
  lines.push('/* AUTO-GENERATED. DO NOT EDIT. */');
  lines.push('// Generated by scripts/generate-container-registry.ts');
  lines.push('');

  if (platform === 'web') {
    lines.push("import { registerWebContainerRenderer } from '../packages/core/src/container-renderers';");
  } else {
    lines.push("import { registerRNContainerRenderer } from '../packages/core/src/container-renderers';");
  }

  specs.forEach((s, i) => {
    const exp = platform === 'web' ? s.webRendererExport : s.rnRendererExport;
    const mod = platform === 'web' ? 'runtime.web' : 'runtime.rn';
    lines.push(`import { ${exp} as r${i} } from '../packages/features/container/${s.featureDir}/src/${mod}';`);
  });

  lines.push('');
  specs.forEach((s, i) => {
    if (platform === 'web') {
      lines.push(`registerWebContainerRenderer('${s.nodeName}', r${i});`);
    } else {
      lines.push(`registerRNContainerRenderer('${s.nodeName}', r${i});`);
    }
  });

  lines.push('');
  lines.push('export {};');
  lines.push('');

  return lines.join('\n');
}

async function main() {
  const dirs = listFeatureDirs();
  const specs: ContainerExtensionSpec[] = [];

  for (const dir of dirs) {
    const spec = await loadExtensionSpec(dir);
    if (!spec) continue;
    spec.featureDir = dir;
    validateSpec(spec, `${dir}/src/extension.ts`);
    specs.push(spec);
  }

  ensureDir(outDir);

  fs.writeFileSync(path.join(outDir, 'container.parsers.ts'), genParsers(specs), 'utf8');
  fs.writeFileSync(path.join(outDir, 'container.renderers.web.ts'), genRenderers(specs, 'web'), 'utf8');
  fs.writeFileSync(path.join(outDir, 'container.renderers.rn.ts'), genRenderers(specs, 'rn'), 'utf8');

  console.log(`[generate-container-registry] generated ${specs.length} container extension(s)`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
