import type { RenderFn, RenderOptions } from '../types.js';

/**
 * The spec shape generated by `@supramark/cli`:
 *
 * - `engines`: engine name -> render function (assembled by the host via factories).
 * - `features`: parser configuration handed to `@supramark/core`.
 */
export interface RenderSpec {
  engines: Record<string, RenderFn>;
  features?: Record<string, unknown>;
}

/**
 * Uses a spec to produce a pure Markdown -> HTML string function.
 *
 * Phase 1 only provides the type skeleton; the actual implementation lands in
 * Phase 5 (currently routed through `@supramark/web`'s `Supramark` +
 * `renderToString`).
 *
 * @example
 * ```ts
 * const render = createRender({ engines, features });
 * const html   = await render(markdown);
 * ```
 */
export function createRender(
  _spec: RenderSpec
): (markdown: string, options?: RenderOptions) => Promise<string> {
  // Returned render fn must satisfy the `Promise<string>` contract; the Phase 5
  // stub only throws, so there is nothing to await yet.
  // eslint-disable-next-line @typescript-eslint/require-await
  return async (_markdown, _options) => {
    throw new Error(
      '[@supramark/engines] createRender is not implemented yet (Phase 5). ' +
        'Track ENGINES_AND_CLI_PLAN.zh.md §8 for progress.'
    );
  };
}
